version: 1.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal
install:
  - choco install opencover codecov
before_build:
  - nuget restore -Verbosity quiet
build_script:
  - msbuild Gcode.sln /verbosity:minimal /p:DebugType=full /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
test_script:
  - OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"/logger:Appveyor Gcode.TestSuite\bin\Debug\Gcode.TestSuite.dll" -filter:"+[Gcode]* -[Gcode.TestSuite]*" -output:".\coverage.xml"
  - codecov -f coverage.xml


artifacts:
  - path: 'MongoFramework\bin\Debug\*.nupkg'
    name: NuGet Package

  - path: coverage.xml
    name: Coverage Report